### ISSUE TITLE
MDS Variant does not set DataCategory correctly

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#535]
# Bug Report

## Description

Submitted Data Categories do not get set properly

**Comment by AbdullahMuk** [comment]
@richardtreier please add more details to the issue (ideally according to the Bug Report template). 

Your contribution will enable another member of the Dev Team to pick-up this issue when they have capacity. Thanks!

**Comment by richardtreier** [comment]
already fixed in main

**Comment by jkbquabeck** [comment]
Mercedes has corrected the offers, Data Category is now there, the problem remains.
Unfortunately, negotiation is still impossible, the offer in the Connector browser cannot be opened when clicking.

![image](https://github.com/sovity/edc-ui/assets/139474964/269ac47e-223b-46b1-b727-479254fb092f)

**Comment by jkbquabeck** [comment]
SOs investigation resulted in the following:

The version tags culd be causing the problem
Broker
![image](https://github.com/sovity/edc-ui/assets/139474964/b964eb9c-a1c1-4827-abb1-dcfad2a7cfb7)

Connector
![image](https://github.com/sovity/edc-ui/assets/139474964/4a907324-28b2-4ae1-a537-089f9c0e14f4)

**Comment by SebastianOpriel** [comment]
Is this bug still
